name: Go
on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x

    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: 'master'
        fetch-depth: '0'

    - name: Generate Git log
      run: |
        git fetch origin +refs/tags/*:refs/tags/*
        GITVER=$(git describe --tags)
        PREVVER=$(git describe --tags --abbrev=0 ${GITVER}~1)
        git log --oneline ${PREVVER}..${GITVER} > gittaglogs.txt

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        CGO_ENABLED=1 go build -ldflags "-s -w" -o flowerss-bot.x86_64
        xz flowerss-bot.x86_64
        
    - name: Release
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          flowerss-bot.x86_64.xz
        prerelease: false
        draft: false
        body_path: gittaglogs.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

